-- IT0049 TFA2 database export
-- Import this file in phpMyAdmin or with the MySQL command-line client.

CREATE DATABASE IF NOT EXISTS pos_database CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE pos_database;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    created_at DATETIME NOT NULL
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL
);

INSERT INTO customers (full_name, email, phone, created_at) VALUES
    ('Maria Santos', 'maria.santos@example.com', '0917-123-4567', '2026-10-09 12:00:00'),
    ('Juan Dela Cruz', 'juan.delacruz@example.com', '0918-234-5678', '2026-10-09 12:00:00'),
    ('Angela Reyes', 'angela.reyes@example.com', '0919-345-6789', '2026-10-09 12:00:00'),
    ('Carlo Mendoza', 'carlo.mendoza@example.com', '0920-456-7890', '2026-10-09 12:00:00'),
    ('Nicole Garcia', 'nicole.garcia@example.com', '0921-567-8901', '2026-10-09 12:00:00');

-- All demo accounts use Password123! for local testing.
-- The stored values were generated by PHP password_hash() and are not plaintext.
INSERT INTO users (username, full_name, password, created_at) VALUES
    ('admin', 'Andrea Lim', '$2y$10$lONP3VOJSC7PApsCUBPRluPhklxNCMGGsBWH28r5yacN6kR7X6GI6', '2026-10-09 12:00:00'),
    ('cashier01', 'Paolo Cruz', '$2y$10$lONP3VOJSC7PApsCUBPRluPhklxNCMGGsBWH28r5yacN6kR7X6GI6', '2026-10-09 12:00:00'),
    ('cashier02', 'Ella Ramos', '$2y$10$lONP3VOJSC7PApsCUBPRluPhklxNCMGGsBWH28r5yacN6kR7X6GI6', '2026-10-09 12:00:00'),
    ('manager01', 'Miguel Torres', '$2y$10$lONP3VOJSC7PApsCUBPRluPhklxNCMGGsBWH28r5yacN6kR7X6GI6', '2026-10-09 12:00:00'),
    ('inventory01', 'Sofia Navarro', '$2y$10$lONP3VOJSC7PApsCUBPRluPhklxNCMGGsBWH28r5yacN6kR7X6GI6', '2026-10-09 12:00:00');
